openapi: 3.1.0
info:
  title: Stores API
  version: 6.6.0
tags:
  - name: Stores
paths:
  /stores:
    get:
      operationId: list
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StoreList"
      tags:
        - Stores
components:
  schemas:
    Store:
      type: object
      required:
        - status
      properties:
        id:
          type: string
        status:
          type: string
          enum:
            - open
            - closed
        tags:
          type: array
          items:
            type: string
    StoreList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Store"
