openapi: 3.1.0
info:
  title: Customers API
  version: 5.6.0
tags:
  - name: Customers
paths:
  /customers:
    get:
      operationId: list
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerList"
      tags:
        - Customers
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
        tags:
          type: array
          items:
            type: string
        metadata:
          $ref: "#/components/schemas/Metadata"
    CustomerList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Customer"
    Metadata:
      type: object
      properties:
        key:
          type: string
