openapi: 3.1.0
info:
  title: Payments API
  version: 9.4.0
tags:
  - name: Payments
paths:
  /payments:
    get:
      operationId: list
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentList"
      tags:
        - Payments
components:
  schemas:
    Payment:
      type: object
      properties:
        id:
          type: string
        tags:
          type: array
          items:
            type: string
        metadata:
          $ref: "#/components/schemas/Metadata"
    PaymentList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Payment"
    Metadata:
      type: object
      properties:
        key:
          type: string
