openapi: 3.1.0
info:
  title: Invoices API
  version: 7.7.0
tags:
  - name: Invoices
paths:
  /invoices:
    get:
      operationId: list
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvoiceList"
      tags:
        - Invoices
components:
  schemas:
    Invoice:
      type: object
      properties:
        id:
          type: string
    InvoiceList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Invoice"
