openapi: 3.1.0
info:
  title: Warehouses API
  version: 6.5.0
tags:
  - name: Warehouses
paths:
  /warehouses:
    get:
      operationId: list
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WarehouseList"
      tags:
        - Warehouses
components:
  schemas:
    Warehouse:
      type: object
      properties:
        id:
          type: string
    WarehouseList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Warehouse"
