openapi: 3.1.0
info:
  title: Departments API
  version: 4.8.0
tags:
  - name: Departments
paths:
  /departments:
    get:
      operationId: list
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DepartmentList"
      tags:
        - Departments
components:
  schemas:
    Department:
      type: object
      properties:
        id:
          type: string
        tags:
          type: array
          items:
            type: string
        metadata:
          $ref: "#/components/schemas/Metadata"
    DepartmentList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Department"
    Metadata:
      type: object
      properties:
        key:
          type: string
