openapi: 3.1.0
info:
  title: Categories API
  version: 2.2.0
tags:
  - name: Categories
paths:
  /categories:
    get:
      operationId: list
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryList"
      tags:
        - Categories
  /categories/{id}:
    get:
      operationId: get
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
      tags:
        - Categories
components:
  schemas:
    Category:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        tags:
          type: array
          items:
            type: string
    CategoryList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Category"
