openapi: 3.1.0
info:
  title: Inventory API
  version: 9.5.0
tags:
  - name: Inventory
paths:
  /inventory:
    get:
      operationId: list
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InventoryList"
      tags:
        - Inventory
components:
  schemas:
    Inventory:
      type: object
      properties:
        id:
          type: string
    InventoryList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Inventory"
