openapi: 3.1.0
info:
  title: Suppliers API
  version: 6.4.0
tags:
  - name: Suppliers
paths:
  /suppliers:
    get:
      operationId: list
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SupplierList"
      tags:
        - Suppliers
components:
  schemas:
    Supplier:
      type: object
      properties:
        id:
          type: string
        tags:
          type: array
          items:
            type: string
        metadata:
          $ref: "#/components/schemas/Metadata"
    SupplierList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Supplier"
    Metadata:
      type: object
      properties:
        key:
          type: string
