openapi: 3.1.0
info:
  title: Employees API
  version: 8.7.0
tags:
  - name: Employees
paths:
  /employees:
    get:
      operationId: list
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmployeeList"
      tags:
        - Employees
components:
  schemas:
    Employee:
      type: object
      required:
        - status
      properties:
        id:
          type: string
        status:
          type: string
          enum:
            - active
            - on_leave
    EmployeeList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Employee"
