openapi: 3.1.0
info:
  title: Customers Service API
  version: 1.6.0
  description: API for managing customers
tags:
  - name: Customers
paths:
  /customers:
    get:
      operationId: Customers_list
      description: List all customers
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerList"
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      tags:
        - Customers
    post:
      operationId: Customers_create
      description: Create a new customer
      responses:
        "201":
          description: Created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
      tags:
        - Customers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerCreate"
  /customers/{id}:
    get:
      operationId: Customers_get
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
      tags:
        - Customers
    delete:
      operationId: Customers_delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Deleted successfully
      tags:
        - Customers
components:
  schemas:
    Customer:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        tags:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
        metadata:
          $ref: "#/components/schemas/Metadata"
    CustomerCreate:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        tags:
          type: array
          items:
            type: string
    CustomerList:
      type: object
      required:
        - items
        - total
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Customer"
        total:
          type: integer
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
    Metadata:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
